### ISSUE TITLE
Account number causing weird behaviour

### ISSUE THREAD

**Issue by faugconti** [edgaremirborbonjimenez/ATM-Solvd-Project#9]
when retrieving from database and displaying the account number we get the number in scientific notation format

AccountDTO{number='**1.2345678E7**', currencies=[CurrencyDTO{name='USD', amount=1700.0, equivalentToDollar=1.0}, CurrencyDTO{name='ARS', amount=197844.0, equivalentToDollar=989.22}, CurrencyDTO{name='MXN', amount=4028.0, equivalentToDollar=20.14}]}

this might be happening because in the database the attribute accounts.number is a double and in domain.Account.number & dtos.AccountDTO.number string is declared.

**Comment by edgaremirborbonjimenez** [comment]
We solved this changing the database number column  type to varchar in Accounts table
